appearance:
  default: light
  switcher: false
  showQuery: false

theme:
  colorPalettes:
    default:
      light:
        - "#E67E22"  # Burnt Orange
        - "#F1C40F"  # Sunny Yellow
        - "#7DCE82"  # Sage Green
        - "#8B5E3C"  # Earthy Brown
        - "#D94F3D"  # Warm Red
        - "#F4D19B"  # Golden Beige
        - "#6B8F4C"  # Olive Green
        - "#5DADE2"  # Soft Blue
 
      dark:
        - "#FF9B40"  # Burnt Orange variant
        - "#FFE066"  # Sunny Yellow variant
        - "#A2E6AA"  # Sage Green variant
        - "#A67855"  # Earthy Brown variant
        - "#FF7763"  # Warm Red variant
        - "#FFE5B2"  # Golden Beige variant
        - "#98B97A"  # Olive Green variant
        - "#82C3FF"  # Soft Blue variant 
  colorScales:
    default:
      light:
        - "#ADD8E6"
        - "#00008B"
      dark:
        - "#ADD8E6"
        - "#00008B"
  colors:
    primary:
      light: "#2563eb"
      dark: "#3b82f6"
    accent:
      light: "#c2410c"
      dark: "#fdba74"
    base:
      light: "#ffffff"
      dark: "#09090b"
    info:
      light: "#0284c7"
      dark: "#38bdf8"
    positive:
      light: "#16a34a"
      dark: "#4ade80"
    warning:
      light: "#f8c900"
      dark: "#fbbf24"
    negative:
      light: "#dc2626"
      dark: "#f87171"
  


plugins:
  components:
    # This loads all of evidence's core charts and UI components
    # You probably don't want to edit this dependency unless you know what you are doing
    "@evidence-dev/core-components": {}

  datasources:
    # You can add additional datasources here by adding npm packages. 
    # Make to also add them to `package.json`.
    "@evidence-dev/bigquery": { }
    "@evidence-dev/csv": { }
    "@evidence-dev/databricks": { }
    "@evidence-dev/duckdb": { }
    "@evidence-dev/mssql": { }
    "@evidence-dev/mysql": { }
    "@evidence-dev/postgres": { }
    "@evidence-dev/source-javascript": { }
    "@evidence-dev/snowflake": { }
    "@evidence-dev/sqlite": { }
    "@evidence-dev/trino": { }
    "@evidence-dev/motherduck": { }
